name: mindcare
description: Una aplicación de bienestar mental y meditación

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^0.13.5
  just_audio: ^0.9.32
  just_audio_web: ^0.4.8
  path_provider: ^2.0.14
  shared_preferences: ^2.1.0
  cached_network_image: ^3.2.3
  flutter_web_plugins:
    sdk: flutter
  url_strategy: ^0.2.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  flutter_stripe: ^9.4.0
  health: ^4.1.1
  firebase_analytics: ^10.0.0
  charts_flutter: ^0.12.0
  wearable_device: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_web_optimizer: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
