name: mindcare
description: Una aplicación de bienestar mental y meditación con IA transversal

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^0.13.5
  
  # Storage & Cache
  shared_preferences: ^2.2.2
  
  # Web Support
  flutter_web_plugins:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_analytics: ^10.7.4
  firebase_remote_config: ^4.3.8
  cloud_functions: ^4.5.8
  
  # Payments
  flutter_stripe: ^10.0.0
  
  # Routing
  go_router: ^13.0.1
  
  # Localization
  flutter_localizations:
    sdk: flutter
  
  # Environment & Config
  flutter_dotenv: ^5.1.0
  
  # UI Components
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  
  # Utils
  uuid: ^4.2.1
  firebase_crashlytics: ^3.5.7
  firebase_performance: ^0.9.4+7
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.1
  firebase_app_check: ^0.2.0
  health: ^13.1.4
  get_it: ^8.2.0
  just_audio: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.5.0
  test: ^1.26.2
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
