name: mindcare
description: Una aplicación de bienestar mental y meditación con IA transversal

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.5.0
  
  # Storage & Cache
  shared_preferences: ^2.2.2
  
  # Web Support
  flutter_web_plugins:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_analytics: ^12.0.1
  firebase_remote_config: ^6.0.1
  cloud_functions: ^6.0.1
  
  # Payments
  flutter_stripe: ^12.0.2
  
  # Routing
  go_router: ^16.2.1
  
  # Localization
  flutter_localizations:
    sdk: flutter
  
  # Environment & Config
  flutter_dotenv: ^6.0.0
  
  # UI Components
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  
  # Utils
  uuid: ^4.2.1
  firebase_crashlytics: ^5.0.1
  firebase_performance: ^0.11.0+1
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.1
  supabase_flutter: ^2.5.0
  intl: ^0.20.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  google_fonts: ^6.2.1
  health: ^13.1.4
  get_it: ^8.2.0
  just_audio: ^0.10.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.5.0
  test: ^1.26.2
  mocktail: ^1.0.4
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.4

  fake_cloud_firestore: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/app_icon.png
    - assets/images/splash.png
    - assets/images/placeholder.png
    - assets/audio/placeholder.mp3
    # Uncomment and configure fonts if needed
    # fonts:
    #   - family: Inter
    #     fonts:
    #       - asset: assets/fonts/Inter-Regular.ttf
    #       - asset: assets/fonts/Inter-Medium.ttf
    #       - asset: assets/fonts/Inter-SemiBold.ttf
    #       - asset: assets/fonts/Inter-Bold.ttf

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true
  web: false
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
