name: rules_test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  firestore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 18
      - run: npm --prefix server/functions ci
      - run: npm --prefix server/functions test
