name: security

on:
  schedule:
    - cron: '0 0 1 */3 *'
  workflow_dispatch:

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Time for scheduled pentest"

  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm --prefix server/functions install
      - run: npm --prefix server/functions audit --production
